// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_BACKBACKCONTROLCOMPONENT__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_BACKBACKCONTROLCOMPONENT__CONTROLLER_H

/************************************************************
 BackBackControlComponent__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "pthread.h"
#include "statemachine/EventPriorityQueue.h"
#include "statemachine/Event_t.h"
#include "statemachine/Pkg_statemachine.h"
#include "statemachine/StructForThread_t.h"

// Include from Include stereotype (header)
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_TIME_EVENT_LOWER_BOUND (0)
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_CHANGE_EVENT_LOWER_BOUND (1)
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_TE_INDEX(id) (id - BACKBACKCONTROLCOMPONENT__CONTROLLER_TIME_EVENT_LOWER_BOUND)
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_CHE_INDEX(id) (id - BACKBACKCONTROLCOMPONENT__CONTROLLER_CHANGE_EVENT_LOWER_BOUND)
#define BACKCONTROLCOMPONENT_BACKCONTROLSTATEMACHINE_REGION1_DEFAULT (0)
#define BACKCONTROLCOMPONENT_PRINCIPALSTATE_REGION1_DEFAULT (0)
#define BACKCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_DEFAULT (0)
#define BACKCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_CHECK (1)
#define BACKCONTROLCOMPONENT_PRINCIPALSTATE_REGION2_DEFAULT (0)
#define BACKCONTROLCOMPONENT_REGION_ID_PRINCIPALSTATE_REGION1 (0)
#define BACKCONTROLCOMPONENT_REGION_ID_PRINCIPALSTATE_REGION2 (1)
#define BACKCONTROLCOMPONENT_BACKCONTROLSTATEMACHINE_REGION1 (0)
#define BACKCONTROLCOMPONENT_PRINCIPALSTATE_REGION1 (1)
#define BACKCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1 (2)
#define BACKCONTROLCOMPONENT_PRINCIPALSTATE_REGION2 (3)
#include "time.h"
#include "pthread.h"
#include "time.h"
#include "sys/time.h"
//the termination of doActivity is implemented in terms of check points that the developers write
//fine-grained code to explicitly use check points to exit doActivity
//#define CHECKPOINT if (systemState == statemachine::EVENT_PROCESSING || systemState == statemachine::STOPPED) {return;}
#define BackBackControlComponent__Controller_THREAD_CREATE(thThread, str) pthread_create(&thThread, NULL, &BackBackControlComponent__Controller::thread_func_wrapper, &str);
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_GET_CONTROL /*mutex synchronization to protect run-to-completion semantics*/ \
		while (!dispatchFlag) {} \
		pthread_mutex_lock(&runToCompletionMutex); \
		while (systemState != statemachine::IDLE) {\
			pthread_cond_wait(&runToCompletionCond, &runToCompletionMutex);\
		}
#define BACKBACKCONTROLCOMPONENT__CONTROLLER_RELEASE_CONTROL systemState = statemachine::IDLE; pthread_cond_signal(&runToCompletionCond); \
				pthread_mutex_unlock(&runToCompletionMutex);
namespace CarFactoryLibrary {
namespace events {
class ErrorDetection;
}
}
namespace CarFactoryLibrary {
namespace events {
class EndOfModule;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class StopProcess;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class RestartAfterEmergencyStop;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class PrepareConveyor;
}
}
namespace CarFactoryLibrary {
namespace events {
class DeliveredCarConveyor;
}
}
namespace CarFactoryLibrary {
namespace events {
class CheckRack;
}
}

// End of Include stereotype (header)

namespace CarFactoryLibrary {
class IModule;
}
namespace CarFactoryLibrary {
namespace CommunicationInterfaces {
class IRoboticArmFloatMotor;
}
}
namespace CarFactoryLibrary {
namespace events {
class EndOfModule;
}
}
namespace CarFactoryLibrary {
namespace events {
class ErrorDetection;
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class ILargeMotor;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILcd;
}
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Back {
class BackControlComponent;
}
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class BackBackControlComponent__Controller: public IPush<
		CarFactoryLibrary::events::EndOfModule>, public IPush<
		CarFactoryLibrary::events::ErrorDetection> {
public:
	/**
	 * 
	 */
	typedef struct State_t {
		bool hasDoActivity;
		//2 is configured as the maximum number of orthogonal regions a composite states can have
		unsigned int actives[2];
		//void (BackBackControlComponent__Controller::*entry)();
		//void (BackBackControlComponent__Controller::*exit)();
		//void (BackBackControlComponent__Controller::*doActivity)();
		State_t() {
			hasDoActivity = false;
			//entry = &BackBackControlComponent__Controller::entry_dft;
			//exit = &BackBackControlComponent__Controller::exit_dft;
			//doActivity = &BackBackControlComponent__Controller::doActivity_dft;
			for (int i = 0; i < 2; i++) {

				actives[i] = STATE_MAX;
			}
		}
	} State_t;

	/**
	 * 
	 */
	enum StateIDEnum {
		/**
		 * 
		 */
		INITIALIZATION_ID,
		/**
		 * 
		 */
		PRINCIPALSTATE_ID,
		/**
		 * 
		 */
		EMNERGENCYSTOPSTATE_ID,
		/**
		 * 
		 */
		CHECK_ID,
		/**
		 * 
		 */
		EMERGENCYBUTTONPRESS_ID,
		/**
		 * 
		 */
		MISPLACE_ID,
		/**
		 * 
		 */
		RESTART_ID,
		/**
		 * 
		 */
		SHOWSTOPGUI_ID,
		/**
		 * 
		 */
		CHECKMESSAGE_ID,
		/**
		 * 
		 */
		RESET_ID,
		/**
		 * 
		 */
		PING_ID,
		/**
		 * 
		 */
		GETSTATUS_ID,
		/**
		 * 
		 */
		LOADCAR_ID,
		/**
		 * 
		 */
		DELIVER_ID,
		/**
		 * 
		 */
		REWIND_ID,
		/**
		 * 
		 */
		ASSEMBLE_ID,
		/**
		 * 
		 */
		STATE_MAX
	};
	/**
	 * 
	 */
	typedef void (BackBackControlComponent__Controller::*FptPointer)();

	/**
	 * 
	 */
	typedef void (BackBackControlComponent__Controller::*RegionFunctionPtr_t)(
			char enter_mode);

	/**
	 * 
	 */
	enum EventId_t {
		/**
		 * 
		 */
		TE_50_MS__ID,
		/**
		 * 
		 */
		ENDOFMODULE_ID,
		/**
		 * 
		 */
		ERRORDETECTION_ID,
		/**
		 * 
		 */
		COMPLETIONEVENT_ID
	};
	/**
	 * 
	 */
	::statemachine::SystemStateEnum_t systemState;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackControlComponent__Controller::State_t states[16];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackControlComponent__Controller::StateIDEnum activeStateID;
	/**
	 * 
	 */
	::statemachine::EventPriorityQueue eventQueue;
	/**
	 * 
	 */
	::statemachine::Event_t* currentEvent;
	/**
	 * 
	 */
	::statemachine::Event_t eventArray[50];
	/**
	 * 
	 */
	bool dispatchFlag;
	/**
	 * 
	 */
	pthread_t threads[STATE_MAX];
	/**
	 * 
	 */
	bool flags[STATE_MAX];
	/**
	 * 
	 */
	pthread_cond_t conds[STATE_MAX];
	/**
	 * 
	 */
	pthread_mutex_t mutexes[STATE_MAX];
	/**
	 * 
	 */
	::statemachine::StructForThread_t threadStructs[STATE_MAX];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackControlComponent__Controller::FptPointer timeEventTable[1];
	/**
	 * 
	 */
	pthread_t timeEventThreads[1];
	/**
	 * 
	 */
	bool timeEventFlags[1];
	/**
	 * 
	 */
	pthread_cond_t timeEventConds[1];
	/**
	 * 
	 */
	pthread_mutex_t timeEventMutexes[1];
	/**
	 * 
	 */
	::statemachine::StructForThread_t timeEventThreadStructs[1];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackControlComponent__Controller::RegionFunctionPtr_t regionTable[2];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackControlComponent__Controller::FptPointer regionExitTable[2];
	/**
	 * 
	 */
	pthread_t dispatchThread;
	/**
	 * 
	 */
	::statemachine::StructForThread_t dispatchStruct;
	/**
	 * 
	 */
	pthread_mutex_t runToCompletionMutex;
	/**
	 * 
	 */
	pthread_cond_t runToCompletionCond;
	/**
	 * 
	 */
	void dispatchEvent();
	/**
	 * 
	 * @param enter_mode 
	 */
	void BackControlStateMachine_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 * @param enter_mode 
	 */
	void PrincipalState_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void PrincipalState_Region1_Exit();
	/**
	 * 
	 * @param enter_mode 
	 */
	void EmnergencyStopState_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void EmnergencyStopState_Region1_Exit();
	/**
	 * 
	 * @param enter_mode 
	 */
	void PrincipalState_Region2_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void PrincipalState_Region2_Exit();
	/**
	 * 
	 * @param origin 
	 */
	BackBackControlComponent__Controller(
			::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Back::BackControlComponent* /*in*/origin);
	/**
	 * 
	 */
	void startBehavior();
	/**
	 * 
	 */
	~BackBackControlComponent__Controller();
	/**
	 * 
	 */
	void stopBehavior();
	/**
	 * 
	 */
	void processTE_50_ms_();
	/**
	 * 
	 * @param sig 
	 */
	void processEndOfModule(
			::CarFactoryLibrary::events::EndOfModule& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(::CarFactoryLibrary::events::EndOfModule& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processErrorDetection(
			::CarFactoryLibrary::events::ErrorDetection& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(::CarFactoryLibrary::events::ErrorDetection& /*in*/sig);
	/**
	 * 
	 */
	void processCompletionEvent();
	/**
	 * 
	 * @param id 
	 */
	void StateEntry(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateExit(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateDoActivity(unsigned int /*in*/id);
	/**
	 * 
	 * @param data 
	 * @return ret 
	 */
	static void* thread_func_wrapper(void* /*in*/data);
	/**
	 * 
	 * @param id 
	 */
	void doCallActivity(int /*in*/id);
	/**
	 * 
	 * @param id 
	 * @param func_type 
	 * @param value 
	 */
	void setFlag(int /*in*/id, char /*in*/func_type, bool /*in*/value);
	/**
	 * 
	 * @param id 
	 * @param duration 
	 */
	void listenTimeEvent(int /*in*/id, int /*in*/duration);
	/**
	 * 
	 * @param id 
	 * @param enter_mode 
	 */
	void regionCall(int /*in*/id, char /*in*/enter_mode);
	/**
	 * 
	 * @param id 
	 */
	void exitRegionCall(int /*in*/id);
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<CarFactoryLibrary::events::ErrorDetection>* get_pErrDetect();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<CarFactoryLibrary::events::EndOfModule>* get_pEndOfMo();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::EV3Brick::ILcd* get_pLCD();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::CarFactoryLibrary::IModule* get_pModule();
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_Shelf(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_RoboticArm(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pStopProcess_Convoyer(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Shelf(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Convoyer(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Robotic(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pPrepare(
			IPush<LegoCarFactoryRefactoringForSync::signals::PrepareConveyor>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pFloatMotor(
			::CarFactoryLibrary::CommunicationInterfaces::IRoboticArmFloatMotor* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pLargeMotorConvoyer(
			::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pLargeMotorPress(
			::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_Press(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Press(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutDelivered(
			IPush<CarFactoryLibrary::events::DeliveredCarConveyor>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutCheckRack(
			IPush<CarFactoryLibrary::events::CheckRack>* /*in*/ref);

private:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Back::BackControlComponent* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of BackBackControlComponent__Controller class header
 ************************************************************/

#endif
