// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define MindsensorsPapyrusLibrary_AbstractClasses_AbstractNumericPad_BODY

/************************************************************
              AbstractNumericPad class body
 ************************************************************/


// include associated header file
#include "MindsensorsPapyrusLibrary/AbstractClasses/AbstractNumericPad.h"

// Derived includes directives
#include "MindsensorsPapyrusLibrary/Interfaces/INumericPad.h"


namespace MindsensorsPapyrusLibrary {
namespace AbstractClasses {

// static attributes (if any)

/**
 * 
 * @return ret 
 */
 ::PrimitiveTypes::Integer AbstractNumericPad::read_current_touched_key() {
}

/**
 * 
 * @return ret 
 */
 ::PrimitiveTypes::Integer AbstractNumericPad::read_next_touched_key() {
}

/**
 * 
 * @return ret 
 * @param dir 
 * @param pattern 
 * @param match 
 */
 ::PrimitiveTypes::Boolean AbstractNumericPad::connect(::EV3PapyrusLibrary::Types::LocalString& /*in*/ dir, ::EV3PapyrusLibrary::Types::LocalString& /*in*/ pattern, ::EV3PapyrusLibrary::Types::MapStringSetString& /*in*/ match) {
}

/**
 * 
 * @return ret 
 */
 ::PrimitiveTypes::Boolean AbstractNumericPad::connected() {
}

/**
 * 
 * @return ret 
 */
 ::PrimitiveTypes::Integer AbstractNumericPad::device_index() {
}

/**
 * 
 * @return ret 
 * @param name 
 */
 ::PrimitiveTypes::Integer AbstractNumericPad::get_attr_int(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param value 
 */
 void AbstractNumericPad::set_attr_int(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name, ::PrimitiveTypes::Integer /*in*/ value) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
 ::EV3PapyrusLibrary::Types::LocalString AbstractNumericPad::get_attr_string(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param value 
 */
 void AbstractNumericPad::set_attr_string(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name, ::EV3PapyrusLibrary::Types::LocalString& /*in*/ value) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
 ::EV3PapyrusLibrary::Types::LocalString AbstractNumericPad::get_attr_line(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param pCur 
 */
 ::EV3PapyrusLibrary::Types::ModeSet AbstractNumericPad::get_attr_set(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name, ::EV3PapyrusLibrary::Types::LocalString* /*in*/ pCur) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
 ::EV3PapyrusLibrary::Types::LocalString AbstractNumericPad::get_attr_from_set(::EV3PapyrusLibrary::Types::LocalString& /*in*/ name) {
}



} // of namespace AbstractClasses
} // of namespace MindsensorsPapyrusLibrary

/************************************************************
              End of AbstractNumericPad class body
 ************************************************************/
