// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Delegatee_Sensors_CppTouchSensor__Delegatee_BODY

/************************************************************
 CppTouchSensor__Delegatee class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Sensors/CppTouchSensor__Delegatee.h"

// Derived includes directives
#include "EV3PapyrusLibrary/ConcreteClasses/ev3devCpp/Sensors/CppTouchSensor.h"
#include "EV3PapyrusLibrary/Interfaces/Sensors/ITouchSensor.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Sensors {

// static attributes (if any)

/**
 * 
 * @param comp 
 */
void CppTouchSensor__Delegatee::setComponent(
		::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Sensors::CppTouchSensor* /*in*/comp) {
	this->component = comp;
	this->get_touchSensorPort();
	this->get_touchSensorPort();
}

/**
 * 
 */
CppTouchSensor__Delegatee::CppTouchSensor__Delegatee() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Interfaces::Sensors::ITouchSensor* CppTouchSensor__Delegatee::get_touchSensorPort() {
	component->touchSensorPort.providedIntf = component;
	return component->touchSensorPort.providedIntf;
}

} // of namespace Sensors
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of CppTouchSensor__Delegatee class body
 ************************************************************/
