// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC_LEGOCARCOMPONENTS_MODULES_BACK_BACKMODULESYSTEM_H
#define LEGOCARFACTORYREFACTORINGFORSYNC_LEGOCARCOMPONENTS_MODULES_BACK_BACKMODULESYSTEM_H

/************************************************************
 BackModuleSystem class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/Pkg_Back.h"

#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackControlComponent.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackConvoyer.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackRoboticArm.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Slaves/SlavePress.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Slaves/SlaveShelf.h"
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/BackBackModuleSystem__Controller.h"

// Include from Include stereotype (header)

#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/Pkg_Back.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackControlComponent.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackConvoyer.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Back/BackRoboticArm.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Slaves/SlavePress.h"
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Slaves/SlaveShelf.h"
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/BackBackModuleSystem__Controller.h"
// End of Include stereotype (header)

namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Back {

/************************************************************/
/**
 * 
 */
class BackModuleSystem {
public:
	/**
	 * 
	 */
	BackConvoyer conveyor;
	/**
	 * 
	 */
	BackRoboticArm robotic_arm;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Slaves::SlaveShelf shelf;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Slaves::SlavePress press;
	/**
	 * 
	 */
	BackControlComponent controller;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::BackBackModuleSystem__Controller backmodulesystemController;
	/**
	 * 
	 */
	BackModuleSystem();
	/**
	 * 
	 */
	void connectorConfiguration();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Back
} // of namespace Modules
} // of namespace LegoCarComponents
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of BackModuleSystem class header
 ************************************************************/

#endif
