// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef EV3PAPYRUSLIBRARY_INTERFACES_ACTUATORS_ILARGEMOTOR_H
#define EV3PAPYRUSLIBRARY_INTERFACES_ACTUATORS_ILARGEMOTOR_H

/************************************************************
 ILargeMotor class header
 ************************************************************/

#include "EV3PapyrusLibrary/Interfaces/Actuators/Pkg_Actuators.h"

#include "EV3PapyrusLibrary/Interfaces/Actuators/IMotor.h"

// Include from Include stereotype (header)
#include <stdint.h>
// End of Include stereotype (header)

namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {

/************************************************************/
/**
 * 
 */
class ILargeMotor: public IMotor {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Actuators
} // of namespace Interfaces
} // of namespace EV3PapyrusLibrary

/************************************************************
 End of ILargeMotor class header
 ************************************************************/

#endif
