// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync_LegoCarComponents_Modules_Chassis_ChassisControlComponent_BODY

/************************************************************
 ChassisControlComponent class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/LegoCarComponents/Modules/Chassis/ChassisControlComponent.h"

// Derived includes directives
#include "CarFactoryLibrary/IModule.h"
#include "CarFactoryLibrary/events/EndOfModule.h"
#include "CarFactoryLibrary/events/ErrorDetection.h"
#include "EV3PapyrusLibrary/Interfaces/EV3Brick/ILcd.h"
#include "LegoCarFactoryRefactoringForSync/signals/PrepareConveyor.h"
#include "LegoCarFactoryRefactoringForSync/signals/RestartAfterEmergencyStop.h"
#include "LegoCarFactoryRefactoringForSync/signals/StopProcess.h"

// Include from Include declaration (body)
void bindPorts(Port& p1, Port& p2) {
}
// End of Include declaration (body)

namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Chassis {

// static attributes (if any)

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice4toSendRestartEventGuard() {

	return ev3Brick.topButton.pressed();
}

/**
 * 
 */
ChassisControlComponent::ChassisControlComponent() :
		chassiscontrolcomponentController(this) {
}

/**
 * 
 * @param sig 
 */
void ChassisControlComponent::effectFromEmergencyStopStatetoMisplace(
		::CarFactoryLibrary::events::ErrorDetection& /*in*/sig) {

	error_detection_is_misplace = sig.is_misplace;
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice2toPrepareConveyorGuard() {

	return current_module != 3;
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice1toStopMotorsGuard() {

	return emergency_button.value(0) && current_module == MASTER_MODULE;
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice0toSendRestartEventGuard() {

	return current_module != CarFactoryLibrary::MASTER_MODULE;
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoicetoSendRestartEventGuard() {

	return ev3Brick.topButton.pressed();
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice13toChooseBackFrontOrderGuard() {

	return init_bluetooth_communication();
}

/**
 * 
 * @return ret 
 */
bool ChassisControlComponent::fromChoice5toSendRestartEventGuard() {

	return current_module != MASTER_MODULE;
}

} // of namespace Chassis
} // of namespace Modules
} // of namespace LegoCarComponents
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of ChassisControlComponent class body
 ************************************************************/
