// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define EV3PapyrusLibrary_AbstractClasses_Sensors_AbstractTouchSensor_BODY

/************************************************************
 AbstractTouchSensor class body
 ************************************************************/

// include associated header file
#include "EV3PapyrusLibrary/AbstractClasses/Sensors/AbstractTouchSensor.h"

// Derived includes directives
#include "EV3PapyrusLibrary/Interfaces/Sensors/ITouchSensor.h"

namespace EV3PapyrusLibrary {
namespace AbstractClasses {
namespace Sensors {

// static attributes (if any)

/**
 * 
 * @return ret 
 * @param index 
 */
::PrimitiveTypes::Integer AbstractTouchSensor::value(unsigned int /*in*/index) {
}

/**
 * 
 * @return ret 
 * @param index 
 */
float AbstractTouchSensor::float_value(unsigned int /*in*/index) {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::type_name() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::bin_data_format() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::CustomVectorChar AbstractTouchSensor::bin_data() {
}

/**
 * 
 * @param v 
 */
void AbstractTouchSensor::set_command(
		::EV3PapyrusLibrary::Types::LocalString /*in*/v) {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::ModeSet AbstractTouchSensor::commands() {
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Integer AbstractTouchSensor::decimals() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::driver_name() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::mode() {
}

/**
 * 
 * @param v 
 */
void AbstractTouchSensor::set_mode(
		::EV3PapyrusLibrary::Types::LocalString /*in*/v) {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::ModeSet AbstractTouchSensor::modes() {
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Integer AbstractTouchSensor::num_values() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::port_name() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::units() {
}

/**
 * 
 * @return ret 
 * @param  
 */
::PrimitiveTypes::Boolean AbstractTouchSensor::connect(
		::EV3PapyrusLibrary::Types::MapStringSetString /*in*/) {
}

/**
 * 
 * @return ret 
 * @param dir 
 * @param pattern 
 * @param match 
 */
::PrimitiveTypes::Boolean AbstractTouchSensor::connect(
		::EV3PapyrusLibrary::Types::LocalString& /*in*/dir,
		::EV3PapyrusLibrary::Types::LocalString& /*in*/pattern,
		::EV3PapyrusLibrary::Types::MapStringSetString& /*in*/match) {
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractTouchSensor::connected() {
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Integer AbstractTouchSensor::device_index() {
}

/**
 * 
 * @return ret 
 * @param name 
 */
::PrimitiveTypes::Integer AbstractTouchSensor::get_attr_int(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param value 
 */
void AbstractTouchSensor::set_attr_int(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name,
		::PrimitiveTypes::Integer /*in*/value) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::get_attr_string(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param value 
 */
void AbstractTouchSensor::set_attr_string(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name,
		::EV3PapyrusLibrary::Types::LocalString /*in*/value) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::get_attr_line(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name) {
}

/**
 * 
 * @return ret 
 * @param name 
 * @param pCur 
 */
::EV3PapyrusLibrary::Types::ModeSet AbstractTouchSensor::get_attr_set(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name,
		::EV3PapyrusLibrary::Types::LocalString /*in*/pCur) {
}

/**
 * 
 * @return ret 
 * @param name 
 */
::EV3PapyrusLibrary::Types::LocalString AbstractTouchSensor::get_attr_from_set(
		::EV3PapyrusLibrary::Types::LocalString /*in*/name) {
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractTouchSensor::isTouch() {
}

} // of namespace Sensors
} // of namespace AbstractClasses
} // of namespace EV3PapyrusLibrary

/************************************************************
 End of AbstractTouchSensor class body
 ************************************************************/
