// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_FRONT_FRONTCONTROLCOMPONENT__DELEGATEE_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_FRONT_FRONTCONTROLCOMPONENT__DELEGATEE_H

/************************************************************
 FrontControlComponent__Delegatee class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Front/Pkg_Front.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "pthread.h"
#include "statemachine/EventQueueAllocationConfiguration.h"
#include "statemachine/Pkg_statemachine.h"
#include "statemachine/StructForThread_t.h"

// Include from Include stereotype (header)
#define FRONTCONTROLCOMPONENT__DELEGATEE_TIME_EVENT_LOWER_BOUND (0)
#define FRONTCONTROLCOMPONENT__DELEGATEE_CHANGE_EVENT_LOWER_BOUND (1)
#define FRONTCONTROLCOMPONENT__DELEGATEE_TE_INDEX(id) (id - FRONTCONTROLCOMPONENT__DELEGATEE_TIME_EVENT_LOWER_BOUND)
#define FRONTCONTROLCOMPONENT__DELEGATEE_CHE_INDEX(id) (id - FRONTCONTROLCOMPONENT__DELEGATEE_CHANGE_EVENT_LOWER_BOUND)
#define FRONTCONTROLCOMPONENT_FRONTCONTROLSTATEMACHINE_REGION1_DEFAULT (0)
#define FRONTCONTROLCOMPONENT_FRONTCONTROLSTATEMACHINE_REGION1_FINALSTATE1 (1)
#define FRONTCONTROLCOMPONENT_PRINCIPALSTATE_REGION1_DEFAULT (0)
#define FRONTCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_DEFAULT (0)
#define FRONTCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_CHECK (1)
#define FRONTCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_WAIT (2)
#define FRONTCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1_EMERGENCYBUTTONPRESS (3)
#define FRONTCONTROLCOMPONENT_PRINCIPALSTATE_REGION2_DEFAULT (0)
#define FRONTCONTROLCOMPONENT_PRINCIPALSTATE_REGION2_CHECKMESSAGE (1)
#define FRONTCONTROLCOMPONENT_REGION_ID_PRINCIPALSTATE_REGION1 (0)
#define FRONTCONTROLCOMPONENT_REGION_ID_PRINCIPALSTATE_REGION2 (1)
#define FRONTCONTROLCOMPONENT_FRONTCONTROLSTATEMACHINE_REGION1 (0)
#define FRONTCONTROLCOMPONENT_PRINCIPALSTATE_REGION1 (1)
#define FRONTCONTROLCOMPONENT_EMNERGENCYSTOPSTATE_REGION1 (2)
#define FRONTCONTROLCOMPONENT_PRINCIPALSTATE_REGION2 (3)
#include "time.h"
#include "pthread.h"
#include "time.h"
#include "sys/time.h"
//the termination of doActivity is implemented in terms of check points that the developers write
//fine-grained code to explicitly use check points to exit doActivity
#ifdef CHECKPOINT 
#undef CHECKPOINT
#endif
#define CHECKPOINT if (frontcontrolcomponentController.systemState == statemachine::EVENT_PROCESSING || frontcontrolcomponentController.systemState == statemachine::STOPPED) {return;}
#define FrontControlComponent__Delegatee_THREAD_CREATE(thThread, str) pthread_create(&thThread, NULL, &FrontControlComponent__Delegatee::thread_func_wrapper, &str);
#define FRONTCONTROLCOMPONENT__DELEGATEE_GET_CONTROL /*mutex synchronization to protect run-to-completion semantics*/ \
		while (!dispatchFlag) {} \
		pthread_mutex_lock(&runToCompletionMutex); \
		while (systemState != statemachine::IDLE || eventQueue.getCompletionSize() > 0) {\
			pthread_cond_wait(&runToCompletionCond, &runToCompletionMutex);\
		}
#define FRONTCONTROLCOMPONENT__DELEGATEE_RELEASE_CONTROL systemState = statemachine::IDLE; pthread_cond_signal(&runToCompletionCond); \
				pthread_mutex_unlock(&runToCompletionMutex);
namespace CarFactoryLibrary {
namespace events {
class ErrorDetection;
}
}
namespace CarFactoryLibrary {
namespace events {
class EndOfModule;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class StopProcess;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class RestartAfterEmergencyStop;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class PrepareConveyor;
}
}
namespace CarFactoryLibrary {
namespace events {
class CheckRack;
}
}
namespace CarFactoryLibrary {
namespace events {
class DeliveredCarConveyor;
}
}
using namespace LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front;

// End of Include stereotype (header)

namespace CarFactoryLibrary {
class IModule;
}
namespace CarFactoryLibrary {
namespace CommunicationInterfaces {
class IRoboticArmFloatMotor;
}
}
namespace CarFactoryLibrary {
namespace events {
class EndOfModule;
}
}
namespace CarFactoryLibrary {
namespace events {
class ErrorDetection;
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class ILargeMotor;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILcd;
}
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Front {
class FrontControlComponent;
}
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Front {

/************************************************************/
/**
 * 
 */
class FrontControlComponent__Delegatee: public IPush<
		CarFactoryLibrary::events::EndOfModule>,
		public IPush<CarFactoryLibrary::events::ErrorDetection>,
		public ::statemachine::EventQueueAllocationConfiguration {
public:
	/**
	 * 
	 */
	typedef struct State_t {
		bool hasDoActivity;
		//2 is configured as the maximum number of orthogonal regions a composite states can have
		unsigned int actives[2];
		//void (FrontControlComponent__Delegatee::*entry)();
		//void (FrontControlComponent__Delegatee::*exit)();
		//void (FrontControlComponent__Delegatee::*doActivity)();
		State_t() {
			hasDoActivity = false;
			//entry = &FrontControlComponent__Delegatee::entry_dft;
			//exit = &FrontControlComponent__Delegatee::exit_dft;
			//doActivity = &FrontControlComponent__Delegatee::doActivity_dft;
			for (int i = 0; i < 2; i++) {

				actives[i] = STATE_MAX;
			}
		}
	} State_t;

	/**
	 * 
	 */
	enum StateIDEnum {
		/**
		 * 
		 */
		INITIALIZATION_ID,
		/**
		 * 
		 */
		PRINCIPALSTATE_ID,
		/**
		 * 
		 */
		EMNERGENCYSTOPSTATE_ID,
		/**
		 * 
		 */
		CHECK_ID,
		/**
		 * 
		 */
		EMERGENCYBUTTONPRESS_ID,
		/**
		 * 
		 */
		MISPLACE_ID,
		/**
		 * 
		 */
		SHOWSTOPGUI_ID,
		/**
		 * 
		 */
		RESTART_ID,
		/**
		 * 
		 */
		CHECKMESSAGE_ID,
		/**
		 * 
		 */
		PING_ID,
		/**
		 * 
		 */
		GETSTATUS_ID,
		/**
		 * 
		 */
		LOADCAR_ID,
		/**
		 * 
		 */
		ASSEMBLE_ID,
		/**
		 * 
		 */
		REWIND_ID,
		/**
		 * 
		 */
		DELIVER_ID,
		/**
		 * 
		 */
		RESET_ID,
		/**
		 * 
		 */
		STATE_MAX
	};
	/**
	 * 
	 */
	typedef void (FrontControlComponent__Delegatee::*FptPointer)();

	/**
	 * 
	 */
	typedef void (FrontControlComponent__Delegatee::*RegionFunctionPtr_t)(
			char enter_mode);

	/**
	 * 
	 */
	enum EventId_t {
		/**
		 * 
		 */
		TE_50_MS__ID,
		/**
		 * 
		 */
		ENDOFMODULE_ID,
		/**
		 * 
		 */
		ERRORDETECTION_ID,
		/**
		 * 
		 */
		COMPLETIONEVENT_ID
	};
	/**
	 * 
	 */
	::statemachine::SystemStateEnum_t systemState;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front::FrontControlComponent__Delegatee::State_t states[16];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front::FrontControlComponent__Delegatee::StateIDEnum activeStateID;
	/**
	 * 
	 */
	bool dispatchFlag;
	/**
	 * 
	 */
	int choice1_CompletionEvent;
	/**
	 * 
	 */
	int choice2_CompletionEvent;
	/**
	 * 
	 */
	int choice_CompletionEvent;
	/**
	 * 
	 */
	pthread_t threads[STATE_MAX];
	/**
	 * 
	 */
	bool flags[STATE_MAX];
	/**
	 * 
	 */
	pthread_cond_t conds[STATE_MAX];
	/**
	 * 
	 */
	pthread_mutex_t mutexes[STATE_MAX];
	/**
	 * 
	 */
	::statemachine::StructForThread_t threadStructs[STATE_MAX];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front::FrontControlComponent__Delegatee::FptPointer timeEventTable[1];
	/**
	 * 
	 */
	pthread_t timeEventThreads[1];
	/**
	 * 
	 */
	bool timeEventFlags[1];
	/**
	 * 
	 */
	pthread_cond_t timeEventConds[1];
	/**
	 * 
	 */
	pthread_mutex_t timeEventMutexes[1];
	/**
	 * 
	 */
	::statemachine::StructForThread_t timeEventThreadStructs[1];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front::FrontControlComponent__Delegatee::RegionFunctionPtr_t regionTable[2];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Front::FrontControlComponent__Delegatee::FptPointer regionExitTable[2];
	/**
	 * 
	 */
	pthread_t dispatchThread;
	/**
	 * 
	 */
	::statemachine::StructForThread_t dispatchStruct;
	/**
	 * 
	 */
	pthread_mutex_t runToCompletionMutex;
	/**
	 * 
	 */
	pthread_cond_t runToCompletionCond;
	/**
	 * 
	 */
	void dispatchEvent();
	/**
	 * 
	 * @param enter_mode 
	 */
	void FrontControlStateMachine_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 * @param enter_mode 
	 */
	void PrincipalState_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void PrincipalState_Region1_Exit();
	/**
	 * 
	 * @param enter_mode 
	 */
	void EmnergencyStopState_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void EmnergencyStopState_Region1_Exit();
	/**
	 * 
	 * @param enter_mode 
	 */
	void PrincipalState_Region2_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void PrincipalState_Region2_Exit();
	/**
	 * 
	 */
	FrontControlComponent__Delegatee();
	/**
	 * 
	 */
	void startBehavior();
	/**
	 * 
	 */
	~FrontControlComponent__Delegatee();
	/**
	 * 
	 */
	void stopBehavior();
	/**
	 * 
	 */
	void processTE_50_ms_();
	/**
	 * 
	 * @param sig 
	 */
	void processEndOfModule(
			::CarFactoryLibrary::events::EndOfModule& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(::CarFactoryLibrary::events::EndOfModule& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processErrorDetection(
			::CarFactoryLibrary::events::ErrorDetection& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(::CarFactoryLibrary::events::ErrorDetection& /*in*/sig);
	/**
	 * 
	 */
	void processCompletionEvent();
	/**
	 * 
	 * @param id 
	 */
	void StateEntry(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateExit(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateDoActivity(unsigned int /*in*/id);
	/**
	 * 
	 * @param data 
	 * @return ret 
	 */
	static void* thread_func_wrapper(void* /*in*/data);
	/**
	 * 
	 * @param id 
	 */
	void doCallActivity(int /*in*/id);
	/**
	 * 
	 * @param id 
	 * @param func_type 
	 * @param value 
	 */
	void setFlag(int /*in*/id, char /*in*/func_type, bool /*in*/value);
	/**
	 * 
	 * @param id 
	 * @param duration 
	 */
	void listenTimeEvent(int /*in*/id, int /*in*/duration);
	/**
	 * 
	 * @param id 
	 * @param enter_mode 
	 */
	void regionCall(int /*in*/id, char /*in*/enter_mode);
	/**
	 * 
	 * @param id 
	 */
	void exitRegionCall(int /*in*/id);
	/**
	 * 
	 * @param comp 
	 */
	void setComponent(
			::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Front::FrontControlComponent* /*in*/comp);
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<CarFactoryLibrary::events::ErrorDetection>* get_pErrDetect();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<CarFactoryLibrary::events::EndOfModule>* get_pEndOfMo();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::EV3Brick::ILcd* get_pLCD();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::CarFactoryLibrary::IModule* get_pModule();
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_Shelf(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_RoboticArm(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pStopProcess_Convoyer(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Shelf(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Convoyer(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Robotic(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pPrepare(
			IPush<LegoCarFactoryRefactoringForSync::signals::PrepareConveyor>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutStopProcess_Press(
			IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutRestart_Press(
			IPush<
					LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pCheckRack(
			IPush<CarFactoryLibrary::events::CheckRack>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pDelivered(
			IPush<CarFactoryLibrary::events::DeliveredCarConveyor>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pIFloatMotor(
			::CarFactoryLibrary::CommunicationInterfaces::IRoboticArmFloatMotor* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pILargeMotor(
			::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pPressILargeMotor(
			::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* /*in*/ref);

private:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Front::FrontControlComponent* component;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Front
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of FrontControlComponent__Delegatee class header
 ************************************************************/

#endif
