// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_EV3PAPYRUSLIBRARY_CPPCOLORSENSOR__DELEGATEE_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_EV3PAPYRUSLIBRARY_CPPCOLORSENSOR__DELEGATEE_H

/************************************************************
 CppColorSensor__Delegatee class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/EV3PapyrusLibrary/Pkg_EV3PapyrusLibrary.h"

// Include from Include stereotype (header)
using namespace LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::EV3PapyrusLibrary;

// End of Include stereotype (header)

namespace EV3PapyrusLibrary {
class CppColorSensor;
}
namespace EV3PapyrusLibrary {
class IColorSensor;
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace EV3PapyrusLibrary {

/************************************************************/
/**
 * 
 */
class CppColorSensor__Delegatee {
public:
	/**
	 * 
	 * @param comp 
	 */
	void setComponent(::EV3PapyrusLibrary::CppColorSensor* /*in*/comp);
	/**
	 * 
	 */
	CppColorSensor__Delegatee();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::IColorSensor* get_colorSensorPort();

private:
	/**
	 * 
	 */
	::EV3PapyrusLibrary::CppColorSensor* component;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace EV3PapyrusLibrary
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of CppColorSensor__Delegatee class header
 ************************************************************/

#endif
