// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Delegatee_Actuators_CppLargeMotor__Delegatee_BODY

/************************************************************
 CppLargeMotor__Delegatee class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Actuators/CppLargeMotor__Delegatee.h"

// Derived includes directives
#include "EV3PapyrusLibrary/ConcreteClasses/ev3devCpp/Actuators/CppLargeMotor.h"
#include "EV3PapyrusLibrary/Interfaces/Actuators/ILargeMotor.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Actuators {

// static attributes (if any)

/**
 * 
 * @param comp 
 */
void CppLargeMotor__Delegatee::setComponent(
		::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppLargeMotor* /*in*/comp) {
	this->component = comp;
	this->get_largeMotorPort();
}

/**
 * 
 */
CppLargeMotor__Delegatee::CppLargeMotor__Delegatee() {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* CppLargeMotor__Delegatee::get_largeMotorPort() {
	component->largeMotorPort.providedIntf = component;
	return component->largeMotorPort.providedIntf;
}

} // of namespace Actuators
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of CppLargeMotor__Delegatee class body
 ************************************************************/
