// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_ACTUATORS_CPPSERVOMOTOR__DELEGATEE_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_ACTUATORS_CPPSERVOMOTOR__DELEGATEE_H

/************************************************************
 CppServoMotor__Delegatee class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Actuators/Pkg_Actuators.h"

// Include from Include stereotype (header)
using namespace LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Actuators;

// End of Include stereotype (header)

namespace EV3PapyrusLibrary {
namespace ConcreteClasses {
namespace ev3devCpp {
namespace Actuators {
class CppServoMotor;
}
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class IServoMotor;
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Actuators {

/************************************************************/
/**
 * 
 */
class CppServoMotor__Delegatee {
public:
	/**
	 * 
	 * @param comp 
	 */
	void setComponent(
			::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* /*in*/comp);
	/**
	 * 
	 */
	CppServoMotor__Delegatee();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::Actuators::IServoMotor* get_servoMotorPort();

private:
	/**
	 * 
	 */
	::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* component;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Actuators
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of CppServoMotor__Delegatee class header
 ************************************************************/

#endif
