// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_BACK_BACKCONVOYER__DELEGATEE_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_BACK_BACKCONVOYER__DELEGATEE_H

/************************************************************
 BackConvoyer__Delegatee class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Back/Pkg_Back.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "pthread.h"
#include "statemachine/EventQueueAllocationConfiguration.h"
#include "statemachine/Pkg_statemachine.h"
#include "statemachine/StructForThread_t.h"

// Include from Include stereotype (header)
#define BACKCONVOYER__DELEGATEE_TIME_EVENT_LOWER_BOUND (0)
#define BACKCONVOYER__DELEGATEE_CHANGE_EVENT_LOWER_BOUND (0)
#define BACKCONVOYER__DELEGATEE_TE_INDEX(id) (id - BACKCONVOYER__DELEGATEE_TIME_EVENT_LOWER_BOUND)
#define BACKCONVOYER__DELEGATEE_CHE_INDEX(id) (id - BACKCONVOYER__DELEGATEE_CHANGE_EVENT_LOWER_BOUND)
#define BACKCONVOYER_BACKCONVEYORSTATEMACHINE_REGION1_DEFAULT (0)
#define BACKCONVOYER_PRINCIPALSTATE_REGION1_DEFAULT (0)
#define BACKCONVOYER_BACKCONVEYORSTATEMACHINE_REGION1 (0)
#define BACKCONVOYER_PRINCIPALSTATE_REGION1 (1)
#include "time.h"
#include "pthread.h"
//the termination of doActivity is implemented in terms of check points that the developers write
//fine-grained code to explicitly use check points to exit doActivity
#ifdef CHECKPOINT 
#undef CHECKPOINT
#endif
#define CHECKPOINT if (backconvoyerController.systemState == statemachine::EVENT_PROCESSING || backconvoyerController.systemState == statemachine::STOPPED) {return;}
#define BackConvoyer__Delegatee_THREAD_CREATE(thThread, str) pthread_create(&thThread, NULL, &BackConvoyer__Delegatee::thread_func_wrapper, &str);
#define BACKCONVOYER__DELEGATEE_GET_CONTROL /*mutex synchronization to protect run-to-completion semantics*/ \
		while (!dispatchFlag) {} \
		pthread_mutex_lock(&runToCompletionMutex); \
		while (systemState != statemachine::IDLE || eventQueue.getCompletionSize() > 0) {\
			pthread_cond_wait(&runToCompletionCond, &runToCompletionMutex);\
		}
#define BACKCONVOYER__DELEGATEE_RELEASE_CONTROL systemState = statemachine::IDLE; pthread_cond_signal(&runToCompletionCond); \
				pthread_mutex_unlock(&runToCompletionMutex);
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class StopProcess;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class RestartAfterEmergencyStop;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class PrepareConveyor;
}
}
namespace CarFactoryLibrary {
namespace events {
class DeliveredCarConveyor;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class GoToPress;
}
}
namespace CarFactoryLibrary {
namespace events {
class CheckRack;
}
}
namespace CarFactoryLibrary {
namespace events {
class ErrorDetection;
}
}
namespace CarFactoryLibrary {
namespace events {
class EndOfModule;
}
}
namespace CarFactoryLibrary {
namespace events {
class PressAssemble;
}
}
using namespace LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Back;

// End of Include stereotype (header)

namespace CarFactoryLibrary {
class IModule;
}
namespace CarFactoryLibrary {
namespace events {
class DeliveredCarConveyor;
}
}
namespace EV3PapyrusLibrary {
class IColorSensor;
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class ILargeMotor;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILcd;
}
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Back {
class BackConvoyer;
}
}
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class GoToPress;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class PrepareConveyor;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class RestartAfterEmergencyStop;
}
}
namespace LegoCarFactoryRefactoringForSync {
namespace signals {
class StopProcess;
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Back {

/************************************************************/
/**
 * 
 */
class BackConvoyer__Delegatee: public IPush<
		LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>,
		public IPush<CarFactoryLibrary::events::DeliveredCarConveyor>,
		public IPush<LegoCarFactoryRefactoringForSync::signals::PrepareConveyor>,
		public IPush<LegoCarFactoryRefactoringForSync::signals::GoToPress>,
		public IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>,
		public ::statemachine::EventQueueAllocationConfiguration {
public:
	/**
	 * 
	 */
	typedef struct State_t {
		bool hasDoActivity;
		//1 is configured as the maximum number of orthogonal regions a composite states can have
		unsigned int actives[1];
		//void (BackConvoyer__Delegatee::*entry)();
		//void (BackConvoyer__Delegatee::*exit)();
		//void (BackConvoyer__Delegatee::*doActivity)();
		State_t() {
			hasDoActivity = false;
			//entry = &BackConvoyer__Delegatee::entry_dft;
			//exit = &BackConvoyer__Delegatee::exit_dft;
			//doActivity = &BackConvoyer__Delegatee::doActivity_dft;
			for (int i = 0; i < 1; i++) {

				actives[i] = STATE_MAX;
			}
		}
	} State_t;

	/**
	 * 
	 */
	enum StateIDEnum {
		/**
		 * 
		 */
		PRINCIPALSTATE_ID,
		/**
		 * 
		 */
		GOINITIALPOSITION_ID,
		/**
		 * 
		 */
		MOVEFORWARD_ID,
		/**
		 * 
		 */
		GOWAITPOSITION_ID,
		/**
		 * 
		 */
		GOCHECKPRESENCEPOSITION_ID,
		/**
		 * 
		 */
		REPLACE_ID,
		/**
		 * 
		 */
		DELIVERCAR_ID,
		/**
		 * 
		 */
		SENDENDOFMODULEEVENT_ID,
		/**
		 * 
		 */
		SENDPRESSASSEMBLEEVENT_ID,
		/**
		 * 
		 */
		MISPLACE_ID,
		/**
		 * 
		 */
		RESTART_ID,
		/**
		 * 
		 */
		STATE_MAX
	};
	/**
	 * 
	 */
	enum EventId_t {
		/**
		 * 
		 */
		RESTARTAFTEREMERGENCYSTOP_ID,
		/**
		 * 
		 */
		DELIVEREDCARCONVEYOR_ID,
		/**
		 * 
		 */
		PREPARECONVEYOR_ID,
		/**
		 * 
		 */
		GOTOPRESS_ID,
		/**
		 * 
		 */
		STOPPROCESS_ID,
		/**
		 * 
		 */
		COMPLETIONEVENT_ID
	};
	/**
	 * 
	 */
	typedef void (BackConvoyer__Delegatee::*FptPointer)();

	/**
	 * 
	 */
	::statemachine::SystemStateEnum_t systemState;
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Back::BackConvoyer__Delegatee::State_t states[11];
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Back::BackConvoyer__Delegatee::StateIDEnum activeStateID;
	/**
	 * 
	 */
	bool dispatchFlag;
	/**
	 * 
	 */
	int choice_CompletionEvent;
	/**
	 * 
	 */
	pthread_t threads[STATE_MAX];
	/**
	 * 
	 */
	bool flags[STATE_MAX];
	/**
	 * 
	 */
	pthread_cond_t conds[STATE_MAX];
	/**
	 * 
	 */
	pthread_mutex_t mutexes[STATE_MAX];
	/**
	 * 
	 */
	::statemachine::StructForThread_t threadStructs[STATE_MAX];
	/**
	 * 
	 */
	pthread_t dispatchThread;
	/**
	 * 
	 */
	::statemachine::StructForThread_t dispatchStruct;
	/**
	 * 
	 */
	pthread_mutex_t runToCompletionMutex;
	/**
	 * 
	 */
	pthread_cond_t runToCompletionCond;
	/**
	 * 
	 */
	void dispatchEvent();
	/**
	 * 
	 * @param enter_mode 
	 */
	void BackConveyorStateMachine_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 * @param enter_mode 
	 */
	void PrincipalState_Region1_Enter(char /*in*/enter_mode);
	/**
	 * 
	 */
	void PrincipalState_Region1_Exit();
	/**
	 * 
	 */
	BackConvoyer__Delegatee();
	/**
	 * 
	 */
	void startBehavior();
	/**
	 * 
	 */
	~BackConvoyer__Delegatee();
	/**
	 * 
	 */
	void stopBehavior();
	/**
	 * 
	 * @param sig 
	 */
	void processRestartAfterEmergencyStop(
			::LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(
			::LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processDeliveredCarConveyor(
			::CarFactoryLibrary::events::DeliveredCarConveyor& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(::CarFactoryLibrary::events::DeliveredCarConveyor& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processPrepareConveyor(
			::LegoCarFactoryRefactoringForSync::signals::PrepareConveyor& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(
			::LegoCarFactoryRefactoringForSync::signals::PrepareConveyor& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processGoToPress(
			::LegoCarFactoryRefactoringForSync::signals::GoToPress& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(
			::LegoCarFactoryRefactoringForSync::signals::GoToPress& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void processStopProcess(
			::LegoCarFactoryRefactoringForSync::signals::StopProcess& /*in*/sig);
	/**
	 * 
	 * @param sig 
	 */
	void push(
			::LegoCarFactoryRefactoringForSync::signals::StopProcess& /*in*/sig);
	/**
	 * 
	 */
	void processCompletionEvent();
	/**
	 * 
	 * @param id 
	 */
	void StateEntry(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateExit(unsigned int /*in*/id);
	/**
	 * 
	 * @param id 
	 */
	void StateDoActivity(unsigned int /*in*/id);
	/**
	 * 
	 * @param data 
	 * @return ret 
	 */
	static void* thread_func_wrapper(void* /*in*/data);
	/**
	 * 
	 * @param id 
	 */
	void doCallActivity(int /*in*/id);
	/**
	 * 
	 * @param id 
	 * @param func_type 
	 * @param value 
	 */
	void setFlag(int /*in*/id, char /*in*/func_type, bool /*in*/value);
	/**
	 * 
	 * @param comp 
	 */
	void setComponent(
			::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Back::BackConvoyer* /*in*/comp);
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<LegoCarFactoryRefactoringForSync::signals::StopProcess>* get_pInStopProcess();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<
			LegoCarFactoryRefactoringForSync::signals::RestartAfterEmergencyStop>* get_pRestart();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<LegoCarFactoryRefactoringForSync::signals::PrepareConveyor>* get_pPrepare();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<CarFactoryLibrary::events::DeliveredCarConveyor>* get_pDelivered();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* get_pILargeMotor();
	/**
	 * 
	 * @return ret 
	 */
	virtual IPush<LegoCarFactoryRefactoringForSync::signals::GoToPress>* get_pGotoProcess();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::IColorSensor* get_sensor();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* get_pMotor();
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pCheckRack(
			IPush<CarFactoryLibrary::events::CheckRack>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pErrDetect(
			IPush<CarFactoryLibrary::events::ErrorDetection>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pEndOfMo_Control(
			IPush<CarFactoryLibrary::events::EndOfModule>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pEndOfMo_Shelf(
			IPush<CarFactoryLibrary::events::EndOfModule>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pEndOfMo_Robotic(
			IPush<CarFactoryLibrary::events::EndOfModule>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pEndOfMo_Press(
			IPush<CarFactoryLibrary::events::EndOfModule>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	virtual void connect_pOutPressAssemble(
			IPush<CarFactoryLibrary::events::PressAssemble>* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pLCD(
			::EV3PapyrusLibrary::Interfaces::EV3Brick::ILcd* /*in*/ref);
	/**
	 * 
	 * @param ref 
	 */
	void connect_pModule(::CarFactoryLibrary::IModule* /*in*/ref);

private:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Back::BackConvoyer* component;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Back
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of BackConvoyer__Delegatee class header
 ************************************************************/

#endif
