// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Controller_AbstractClassesAbstractSensorMux__Controller_BODY

/************************************************************
 AbstractClassesAbstractSensorMux__Controller class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/AbstractClassesAbstractSensorMux__Controller.h"

// Derived includes directives
#include "MindsensorsPapyrusLibrary/AbstractClasses/AbstractSensorMux.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

// static attributes (if any)

/**
 * 
 * @param origin 
 */
AbstractClassesAbstractSensorMux__Controller::AbstractClassesAbstractSensorMux__Controller(
		::MindsensorsPapyrusLibrary::AbstractClasses::AbstractSensorMux* /*in*/origin) :
		p_origin(origin) {
}

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of AbstractClassesAbstractSensorMux__Controller class body
 ************************************************************/
