// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ABSTRACTCLASSESABSTRACTSENSORMUX__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ABSTRACTCLASSESABSTRACTSENSORMUX__CONTROLLER_H

/************************************************************
 AbstractClassesAbstractSensorMux__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

namespace MindsensorsPapyrusLibrary {
namespace AbstractClasses {
class AbstractSensorMux;
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class AbstractClassesAbstractSensorMux__Controller {
public:
	/**
	 * 
	 * @param origin 
	 */
	AbstractClassesAbstractSensorMux__Controller(
			::MindsensorsPapyrusLibrary::AbstractClasses::AbstractSensorMux* /*in*/origin);

private:
	/**
	 * 
	 */
	::MindsensorsPapyrusLibrary::AbstractClasses::AbstractSensorMux* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of AbstractClassesAbstractSensorMux__Controller class header
 ************************************************************/

#endif
