// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ACTUATORSCPPLARGEMOTOR__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ACTUATORSCPPLARGEMOTOR__CONTROLLER_H

/************************************************************
 ActuatorsCppLargeMotor__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

namespace EV3PapyrusLibrary {
namespace ConcreteClasses {
namespace ev3devCpp {
namespace Actuators {
class CppLargeMotor;
}
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class ILargeMotor;
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class ActuatorsCppLargeMotor__Controller {
public:
	/**
	 * 
	 * @param origin 
	 */
	ActuatorsCppLargeMotor__Controller(
			::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppLargeMotor* /*in*/origin);
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* get_largeMotorPort();

private:
	/**
	 * 
	 */
	::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppLargeMotor* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of ActuatorsCppLargeMotor__Controller class header
 ************************************************************/

#endif
