// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_CARFACTORYLIBRARYMODULE__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_CARFACTORYLIBRARYMODULE__CONTROLLER_H

/************************************************************
 CarFactoryLibraryModule__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

namespace CarFactoryLibrary {
class IModule;
}
namespace CarFactoryLibrary {
class Module;
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILcd;
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class CarFactoryLibraryModule__Controller {
public:
	/**
	 * 
	 * @param origin 
	 */
	CarFactoryLibraryModule__Controller(
			::CarFactoryLibrary::Module* /*in*/origin);
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::EV3Brick::ILcd* get_pLCD();
	/**
	 * 
	 * @return ret 
	 */
	virtual ::CarFactoryLibrary::IModule* get_pModule();

private:
	/**
	 * 
	 */
	::CarFactoryLibrary::Module* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of CarFactoryLibraryModule__Controller class header
 ************************************************************/

#endif
