// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Controller_EV3PapyrusLibraryCppColorSensor__Controller_BODY

/************************************************************
 EV3PapyrusLibraryCppColorSensor__Controller class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/EV3PapyrusLibraryCppColorSensor__Controller.h"

// Derived includes directives
#include "EV3PapyrusLibrary/CppColorSensor.h"
#include "EV3PapyrusLibrary/IColorSensor.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

// static attributes (if any)

/**
 * 
 * @param origin 
 */
EV3PapyrusLibraryCppColorSensor__Controller::EV3PapyrusLibraryCppColorSensor__Controller(
		::EV3PapyrusLibrary::CppColorSensor* /*in*/origin) :
		p_origin(origin) {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::IColorSensor* EV3PapyrusLibraryCppColorSensor__Controller::get_colorSensorPort() {
	p_origin->colorSensorPort.providedIntf = p_origin;
	return p_origin->colorSensorPort.providedIntf;
}

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of EV3PapyrusLibraryCppColorSensor__Controller class body
 ************************************************************/
