// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Controller_EV3PapyrusLibraryAbstractColorSensor__Controller_BODY

/************************************************************
 EV3PapyrusLibraryAbstractColorSensor__Controller class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/EV3PapyrusLibraryAbstractColorSensor__Controller.h"

// Derived includes directives
#include "EV3PapyrusLibrary/AbstractColorSensor.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

// static attributes (if any)

/**
 * 
 * @param origin 
 */
EV3PapyrusLibraryAbstractColorSensor__Controller::EV3PapyrusLibraryAbstractColorSensor__Controller(
		::EV3PapyrusLibrary::AbstractColorSensor* /*in*/origin) :
		p_origin(origin) {
}

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of EV3PapyrusLibraryAbstractColorSensor__Controller class body
 ************************************************************/
