// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MINDSENSORSPAPYRUSLIBRARY_INTERFACES_ISENSORMUX_H
#define MINDSENSORSPAPYRUSLIBRARY_INTERFACES_ISENSORMUX_H

/************************************************************
 ISensorMux class header
 ************************************************************/

#include "MindsensorsPapyrusLibrary/Interfaces/Pkg_Interfaces.h"

#include "EV3PapyrusLibrary/Interfaces/EV3Brick/IDevice.h"
#include "EV3PapyrusLibrary/Types/Pkg_Types.h"

namespace MindsensorsPapyrusLibrary {
namespace Interfaces {

/************************************************************/
/**
 * 
 */
class ISensorMux: public ::EV3PapyrusLibrary::Interfaces::EV3Brick::IDevice {
public:
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::LocalString type_name() = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::LocalString bin_data_format() = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::CustomVectorChar bin_data() = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::LocalString driver_name() = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::LocalString mode() = 0;
	/**
	 * 
	 * @param v 
	 */
	virtual void set_mode(::EV3PapyrusLibrary::Types::LocalString /*in*/v) = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::ModeSet modes() = 0;
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Types::LocalString port_name() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Interfaces
} // of namespace MindsensorsPapyrusLibrary

/************************************************************
 End of ISensorMux class header
 ************************************************************/

#endif
