// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_ROOF_ROOFMODULESYSTEM__DELEGATEE_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__DELEGATEE_ROOF_ROOFMODULESYSTEM__DELEGATEE_H

/************************************************************
 RoofModuleSystem__Delegatee class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Delegatee/Roof/Pkg_Roof.h"

// Include from Include stereotype (header)
using namespace LegoCarFactoryRefactoringForSync::__Architecture__Delegatee::Roof;

// End of Include stereotype (header)

namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Roof {
class RoofModuleSystem;
}
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Delegatee {
namespace Roof {

/************************************************************/
/**
 * 
 */
class RoofModuleSystem__Delegatee {
public:
	/**
	 * 
	 * @param comp 
	 */
	void setComponent(
			::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Roof::RoofModuleSystem* /*in*/comp);
	/**
	 * 
	 */
	RoofModuleSystem__Delegatee();
	/**
	 * 
	 */
	void createConnections();

private:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Roof::RoofModuleSystem* component;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Roof
} // of namespace __Architecture__Delegatee
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of RoofModuleSystem__Delegatee class header
 ************************************************************/

#endif
