// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define EV3PapyrusLibrary_AbstractClasses_EV3Brick_AbstractBlutooth_BODY

/************************************************************
 AbstractBlutooth class body
 ************************************************************/

// include associated header file
#include "EV3PapyrusLibrary/AbstractClasses/EV3Brick/AbstractBlutooth.h"

// Derived includes directives

namespace EV3PapyrusLibrary {
namespace AbstractClasses {
namespace EV3Brick {

// static attributes (if any)

/**
 * 
 * @param name 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractBlutooth::connect(
		::EV3PapyrusLibrary::Types::LocalString& /*in*/name) {
}

/**
 * 
 * @param name 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractBlutooth::accept_connection(
		::EV3PapyrusLibrary::Types::LocalString& /*in*/name) {
}

/**
 * 
 * @param name 
 * @param result 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractBlutooth::read(
		::EV3PapyrusLibrary::Types::LocalString& /*in*/name,
		::EV3PapyrusLibrary::Types::LocalString* /*in*/result) {
}

/**
 * 
 * @param name 
 * @param msg 
 * @return ret 
 */
::PrimitiveTypes::Boolean AbstractBlutooth::write(
		::EV3PapyrusLibrary::Types::LocalString& /*in*/name,
		::EV3PapyrusLibrary::Types::LocalString& /*in*/msg) {
}

} // of namespace EV3Brick
} // of namespace AbstractClasses
} // of namespace EV3PapyrusLibrary

/************************************************************
 End of AbstractBlutooth class body
 ************************************************************/
