// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CARFACTORYLIBRARY_EVENTS_PRESSASSEMBLE_H
#define CARFACTORYLIBRARY_EVENTS_PRESSASSEMBLE_H

/************************************************************
 PressAssemble class header
 ************************************************************/

#include "CarFactoryLibrary/events/Pkg_events.h"

namespace CarFactoryLibrary {
namespace events {

/************************************************************/
/**
 * 
 */
class PressAssemble {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace events
} // of namespace CarFactoryLibrary

/************************************************************
 End of PressAssemble class header
 ************************************************************/

#endif
