// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ACTUATORSCPPSERVOMOTOR__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_ACTUATORSCPPSERVOMOTOR__CONTROLLER_H

/************************************************************
 ActuatorsCppServoMotor__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

namespace EV3PapyrusLibrary {
namespace ConcreteClasses {
namespace ev3devCpp {
namespace Actuators {
class CppServoMotor;
}
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace Actuators {
class IServoMotor;
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class ActuatorsCppServoMotor__Controller {
public:
	/**
	 * 
	 * @param origin 
	 */
	ActuatorsCppServoMotor__Controller(
			::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* /*in*/origin);
	/**
	 * 
	 * @return ret 
	 */
	virtual ::EV3PapyrusLibrary::Interfaces::Actuators::IServoMotor* get_servoMotorPort();
	/**
	 * 
	 * @param origin 
	 */
	ActuatorsCppServoMotor__Controller(
			::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* /*in*/origin);

private:
	/**
	 * 
	 */
	::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* p_origin;
	/**
	 * 
	 */
	::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppServoMotor* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of ActuatorsCppServoMotor__Controller class header
 ************************************************************/

#endif
