// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define LegoCarFactoryRefactoringForSync___Architecture__Controller_ActuatorsCppLargeMotor__Controller_BODY

/************************************************************
 ActuatorsCppLargeMotor__Controller class body
 ************************************************************/

// include associated header file
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/ActuatorsCppLargeMotor__Controller.h"

// Derived includes directives
#include "EV3PapyrusLibrary/ConcreteClasses/ev3devCpp/Actuators/CppLargeMotor.h"
#include "EV3PapyrusLibrary/Interfaces/Actuators/ILargeMotor.h"

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

// static attributes (if any)

/**
 * 
 * @param origin 
 */
ActuatorsCppLargeMotor__Controller::ActuatorsCppLargeMotor__Controller(
		::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppLargeMotor* /*in*/origin) :
		p_origin(origin) {
}

/**
 * 
 * @return ret 
 */
::EV3PapyrusLibrary::Interfaces::Actuators::ILargeMotor* ActuatorsCppLargeMotor__Controller::get_largeMotorPort() {
	p_origin->largeMotorPort.providedIntf = p_origin;
	return p_origin->largeMotorPort.providedIntf;
}

/**
 * 
 * @param origin 
 */
ActuatorsCppLargeMotor__Controller::ActuatorsCppLargeMotor__Controller(
		::EV3PapyrusLibrary::ConcreteClasses::ev3devCpp::Actuators::CppLargeMotor* /*in*/origin) :
		p_origin(origin) {
}

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of ActuatorsCppLargeMotor__Controller class body
 ************************************************************/
