// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_FRONTFRONTMODULESYSTEM__CONTROLLER_H
#define LEGOCARFACTORYREFACTORINGFORSYNC___ARCHITECTURE__CONTROLLER_FRONTFRONTMODULESYSTEM__CONTROLLER_H

/************************************************************
 FrontFrontModuleSystem__Controller class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/Pkg___Architecture__Controller.h"

namespace LegoCarFactoryRefactoringForSync {
namespace LegoCarComponents {
namespace Modules {
namespace Front {
class FrontModuleSystem;
}
}
}
}

namespace LegoCarFactoryRefactoringForSync {
namespace __Architecture__Controller {

/************************************************************/
/**
 * 
 */
class FrontFrontModuleSystem__Controller {
public:
	/**
	 * 
	 * @param origin 
	 */
	FrontFrontModuleSystem__Controller(
			::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Front::FrontModuleSystem* /*in*/origin);
	/**
	 * 
	 */
	void createConnections();

private:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::LegoCarComponents::Modules::Front::FrontModuleSystem* p_origin;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace __Architecture__Controller
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
 End of FrontFrontModuleSystem__Controller class header
 ************************************************************/

#endif
