// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef LEGOCARFACTORYREFACTORINGFORSYNC_SIGNALS_PREPARECONVEYOR_H
#define LEGOCARFACTORYREFACTORINGFORSYNC_SIGNALS_PREPARECONVEYOR_H

/************************************************************
              PrepareConveyor class header
 ************************************************************/

#include "LegoCarFactoryRefactoringForSync/signals/Pkg_signals.h"

#include "CarFactoryLibrary/Pkg_CarFactoryLibrary.h"



namespace LegoCarFactoryRefactoringForSync {
namespace signals {

/************************************************************/
/**
 * 
 */
class PrepareConveyor {
	public:
	/**
	 * 
	 */
	 ::CarFactoryLibrary::Colors color;


};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/


/* Inline functions                                         */


} // of namespace signals
} // of namespace LegoCarFactoryRefactoringForSync

/************************************************************
              End of PrepareConveyor class header
 ************************************************************/

#endif
