// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef EV3PAPYRUSLIBRARY_EV3BRICKPACKAGE_CPPEV3BRICK_H
#define EV3PAPYRUSLIBRARY_EV3BRICKPACKAGE_CPPEV3BRICK_H

/************************************************************
 CppEV3Brick class header
 ************************************************************/

#include "EV3PapyrusLibrary/EV3BrickPackage/Pkg_EV3BrickPackage.h"

#include "EV3PapyrusLibrary/EV3BrickPackage/AbstractEV3Brick.h"
#include "LegoCarFactoryRefactoringForSync/__Architecture__Controller/EV3BrickPackageCppEV3Brick__Controller.h"

// Include from Include stereotype (header)
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILed;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class IButton;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ILcd;
}
}
}
namespace EV3PapyrusLibrary {
namespace Interfaces {
namespace EV3Brick {
class ISound;
}
}
}

// End of Include stereotype (header)

namespace EV3PapyrusLibrary {
namespace EV3BrickPackage {

/************************************************************/
/**
 * 
 */
class CppEV3Brick: public AbstractEV3Brick {
public:
	/**
	 * 
	 */
	::LegoCarFactoryRefactoringForSync::__Architecture__Controller::EV3BrickPackageCppEV3Brick__Controller cppev3brickController;
	/**
	 * 
	 */
	void allLedOn();
	/**
	 * 
	 */
	void allLedOff();
	/**
	 * 
	 */
	CppEV3Brick();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace EV3BrickPackage
} // of namespace EV3PapyrusLibrary

/************************************************************
 End of CppEV3Brick class header
 ************************************************************/

#endif
